### ISSUE TITLE
local network exposure with `vite --host` fails to render in browser. 

### ISSUE THREAD

**Issue by kevzettler** [matrix-org/thirdroom#406]
I would like to host an instance over local network to share with other users. `vite --host` launches successfully and gives a local ip address to connect too. 
```
thirdroom % vite --host
Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating

  VITE v3.1.1  ready in 279 ms

  ➜  Local:   http://localhost:3000/
  ➜  Network: http://192.168.86.224:3000/
  ➜  Network: http://10.17.18.2:3000/
  ```

When I access the URL http://192.168.86.224:3000/  the browser renders a blank screen with some console errors. Seems to be cross origin policy issues.

```
The Cross-Origin-Opener-Policy header has been ignored, because the URL's origin was untrustworthy. It was defined either in the final response or a redirect. Please deliver the response using the HTTPS protocol. You can also use the 'localhost' origin instead. See https://www.w3.org/TR/powerful-features/#potentially-trustworthy-origin and https://html.spec.whatwg.org/#the-cross-origin-opener-policy-header.
hydrogen.es.js:7499 Uncaught TypeError: Cannot read properties of undefined (reading 'deriveBits')
    at new Crypto (hydrogen.es.js:7499:23)
    at new Platform (hydrogen.es.js:8720:21)
    at initHydrogen (HydrogenRootView.tsx:161:20)
    at mountState (react-dom.development.js:15626:20)
    at Object.useState (react-dom.development.js:16248:16)
    at useState (react.development.js:1508:21)
    at HydrogenRootView (HydrogenRootView.tsx:404:78)
    at renderWithHooks (react-dom.development.js:14985:18)
    at mountIndeterminateComponent (react-dom.development.js:17811:13)
    at beginWork (react-dom.development.js:19049:16)
react-dom.development.js:20085 The above error occurred in the <HydrogenRootView> component:

    at HydrogenRootView (http://192.168.86.224:3000/src/ui/views/HydrogenRootView.tsx:350:8)
    at Routes (http://192.168.86.224:3000/node_modules/.vite/deps/react-router-dom.js?v=c13e93e7:1144:5)
    at App
    at Router (http://192.168.86.224:3000/node_modules/.vite/deps/react-router-dom.js?v=c13e93e7:1091:15)
    at BrowserRouter (http://192.168.86.224:3000/node_modules/.vite/deps/react-router-dom.js?v=c13e93e7:1220:5)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
logCapturedError @ react-dom.development.js:20085
hydrogen.es.js:7499 Uncaught TypeError: Cannot read properties of undefined (reading 'deriveBits')
    at new Crypto (hydrogen.es.js:7499:23)
    at new Platform (hydrogen.es.js:8720:21)
    at initHydrogen (HydrogenRootView.tsx:161:20)
    at mountState (react-dom.development.js:15626:20)
    at Object.useState (react-dom.development.js:16248:16)
    at useState (react.development.js:1508:21)
    at HydrogenRootView (HydrogenRootView.tsx:404:78)
    at renderWithHooks (react-dom.development.js:14985:18)
    at mountIndeterminateComponent (react-dom.development.js:17811:13)
    at beginWork (react-dom.development.js:19049:16)
    ```
    
    
    Is there any alternative solution for this?

**Comment by robertlong** [comment]
I'm pretty sure in order for this to work you'd need to add a self-signed SSL cert and run with the vite https config set. I'm not sure if that would be the end of your CORS/COOP/COEP problems or not though.

Here's some more info on Secure Contexts:

https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts

**Comment by kevzettler** [comment]
@robertlong 
I should add that I have no problems on `localhost:3000` so if its CORS then isn't a matter of host name conflict? something hardcoded to `localhost:3000` vs `192.168.86.224:3000` if it was SSL cert would it not also be an issue on `localhost` host name?

**Comment by robertlong** [comment]
On that page I link there's some info on this:

> Locally-delivered resources such as those with http://127.0.0.1 URLs, http://localhost and http://*.localhost URLs (e.g. http://dev.whatever.localhost/), and file:// URLs are also considered to have been delivered securely.

> Resources that are not local, to be considered secure, must meet the following criteria:
>
>    must be served over https:// or wss:// URLs
>    the security properties of the network channel used to deliver the resource must not be considered deprecated

So you'll need the ssl cert for that

**Comment by kevzettler** [comment]
ah I see that in the browser error message now that 'localhost' origin is an exception

**Comment by kevzettler** [comment]
ok I was able to accomplish this by using the [vite-plugin-mkcert](https://github.com/liuweiGL/vite-plugin-mkcert) package.

```
npm i vite-plugin-mkcert -D
```

vite.config.js
```
import { defineConfig } from 'vite'
import mkcert from 'vite-plugin-mkcert'

export default defineConfig({
  server: { https: true },
  plugins: [ mkcert() ]
})
```

maybe worth considering for adding to dev builds or something going to close and leave this as bread crumb for future searchers
