### ISSUE TITLE
Production build throws error window.crypto.subtle is undefined?

### ISSUE THREAD

**Issue by kevzettler** [matrix-org/thirdroom#431]
**Describe the bug**

getting an error on my production domain when I copy the `dist` directory  from `yarn build` to nginx static hosting.

```
react-dom.production.min.js:216 TypeError: Cannot read properties of undefined (reading 'deriveBits')
    at new MD (hydrogen.es.js:7501:23)
    at new oO (hydrogen.es.js:8721:21)
    at XF (HydrogenRootView.tsx:161:20)
    at Object.Qs [as useState] (react-dom.production.min.js:165:102)
    at X.useState (react.production.min.js:23:281)
    at nB (HydrogenRootView.tsx:404:78)
    at lp (react-dom.production.min.js:157:137)
    at mb (react-dom.production.min.js:267:460)
    at hb (react-dom.production.min.js:250:347)
    at uT (react-dom.production.min.js:250:278)
```

The hydrogen.es.js line comes from the implementation of this `Crypto` class

```
class Crypto {
  constructor(cryptoExtras) {
    const crypto2 = window.crypto || window.msCrypto;
    const subtleCrypto = crypto2.subtle || crypto2.webkitSubtle;
    this._subtleCrypto = subtleCrypto;
    if (!subtleCrypto.deriveBits && (cryptoExtras == null ? void 0 : cryptoExtras.aesjs)) {
      this.aes = new AESLegacyCrypto(cryptoExtras.aesjs, crypto2);
    } else {
      this.aes = new AESCrypto(subtleCrypto, crypto2);
    }
    this.hmac = new HMACCrypto(subtleCrypto);
    this.derive = new DeriveCrypto(subtleCrypto, this, cryptoExtras);
  }
 ```
 
 If I log from the browser console This `subtle` property is not defined
 
<img width="694" alt="image" src="https://user-images.githubusercontent.com/126209/202052028-c2e13cf8-07c2-456b-a73b-63dfef370ba9.png">

I can host the same static HTML/JS code on localhost and this error doesn't happen. I suspect maybe there is some server header I need to add to enable?

**Comment by kevzettler** [comment]
This was an SSL cert error on my hosting server
